use soroban_sdk::contracterror;

/// Marketplace contract errors.
#[contracterror]
#[derive(Clone, Debug, Copy, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum MarketplaceError {
    NotOwner = 1,
    AssetNotFound = 2,
    AssetInactive = 3,
    SelfPurchase = 4,
    InvalidPrice = 5,
    AssetLimitReached = 6,
    LicenseAlreadyExists = 7,
    Unauthorized = 8,
    InvalidMetadata = 9,
    InvalidPayment = 10,
    AlreadyPurchased = 11,
    AlreadyListed = 12,
    NotListed = 13,
    InvalidAssetState = 14,
    ArithmeticError = 15,
    EscrowAlreadyReleased = 16,
    DisputeWindowClosed = 17,
    NotArbitrator = 18,
    EscrowNotFound = 19,
    EscrowDisputed = 20,
    DisputeNotFound = 21,
    DisputeAlreadyResolved = 22,
    InvalidRefundBps = 23,
    NoArbitratorVotes = 24,
    AuctionNotFound = 25,
    AuctionPhaseError = 26,
    BidNotCommitted = 27,
    CommitmentMismatch = 28,
    InvalidBidAmount = 29,
    InvalidAuctionParams = 30,
    LicenseNotFound = 31,
    InvalidSubscriptionPeriod = 32,
    SubscriptionExpired = 33,
    SubscriptionNotActive = 34,
    ProrationError = 35,
    BidAlreadyRevealed = 36,
    TokenMismatch = 37,
    PolicyNotFound = 38,
    InvalidThreshold = 39,
    ProposalNotFound = 40,
    NotASigner = 41,
    SignerAlreadyApproved = 42,
    ProposalNotPending = 43,
    ProposalExpired = 44,
    BondNotFound = 45,
    InsufficientBond = 46,
    BondWithdrawalBlocked = 47,
    InvalidDisputeRound = 48,
    DisputeNotActive = 49,
    AlreadyRevealed = 50,
    AlreadyResponded = 51,
    ResponseWindowExpired = 52,
    RevealWindowExpired = 53,
    AlreadyEscalated = 54,
    InvalidRuling = 55,
    ArbiterNotFound = 56,
    ArbiterAlreadyExists = 57,
    DisputeNotFinalRound = 58,
}
